# Builder docker image

FROM maven:3.9.9-eclipse-temurin-21 as build
WORKDIR /app
COPY . .
RUN mvn clean package

FROM eclipse-temurin:21.0.6_7-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
CMD ["java", "-jar", "app.jar"]


# maven image size: 200 MB
# eclipse-temurin image size: 69MB

# Build the image
# docker build -t app .

# Run the container
# docker run -d --name app app

# Check the logs
# docker logs app
